server:
  port: 9044
spring:
  application:
    name: order-add
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ## 如果后端项目服务器和数据库服务器不在同一台主机，则需要修改localhost为数据库服务器的ip地址
    url: jdbc:mysql://localhost:3306/fm-shop?rewriteBatchedStatements=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://qingfeng:123456@localhost:8761/eureka

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qingfeng.fm.entity
