server:
  port: 8014
spring:
  application:
    name: api-order-submit
  redis:
    host: 47.108.28.239
    password: 123456
    port: 6379
    database: 0
  zipkin:
    enabled: true
    base-url: http://localhost:9411   # zipkin server 的地址
  sleuth:
    sampler:
      probability: 1

# rabbitmq的配置
  rabbitmq:
    host: 47.108.28.239
    port: 5672
    virtual-host: host1
    username: qingfeng
    password: admin123


eureka:
  client:
    service-url:
      defaultZone: http://qingfeng:123456@localhost:8761/eureka

## 开启熔断器机制
feign:
  hystrix:
    enabled: true
