spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      ## 如果后端项目服务器和数据库服务器不在同一台主机，则需要修改localhost为数据库服务器的ip地址
      url: jdbc:mysql://47.108.28.239:3306/fm-shop?rewriteBatchedStatements=true&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: admin123

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qingfeng.fm.entity

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error