server:
  port: 9044
spring:
  application:
    name: order-timeout-cancle

eureka:
  client:
    service-url:
      defaultZone: http://qingfeng:123456@localhost:8761/eureka
feign:
  hystrix:
    enabled: true
